CREATE TABLE [dbo].[alicuotas_iva_cpp] (
    [ALICUOTA_CPP_ID]               TINYINT        NOT NULL,
    [ALICUOTA]                      DECIMAL (9, 2) NULL,
    [COLUMNA_SUBDIARIO_IVA]         TINYINT        NULL,
    [COLUMNA_SUBDIARIO_FACTURACION] TINYINT        NULL,
    [LETRA_FACTURA]                 VARCHAR (1)    NULL,
    [CUENTA_CONTABLE]               VARCHAR (30)   NULL,
    PRIMARY KEY CLUSTERED ([ALICUOTA_CPP_ID] ASC),
    UNIQUE NONCLUSTERED ([ALICUOTA] ASC, [LETRA_FACTURA] ASC),
    UNIQUE NONCLUSTERED ([COLUMNA_SUBDIARIO_IVA] ASC, [LETRA_FACTURA] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ALI101_ALICUOTAS_CP_X_ALICUOTA]
    ON [dbo].[alicuotas_iva_cpp]([ALICUOTA] ASC);


GO

