CREATE TABLE [dbo].[Armarios] (
    [ARMARIO_ID]   INT          NOT NULL,
    [DESCRIPCION]  VARCHAR (30) NULL,
    [CODIGO_CALLE] INT          NULL,
    [NUMERO]       INT          NULL,
    [LUGAR]        VARCHAR (30) NULL,
    PRIMARY KEY CLUSTERED ([ARMARIO_ID] ASC),
    UNIQUE NONCLUSTERED ([ARMARIO_ID] ASC),
    UNIQUE NONCLUSTERED ([DESCRIPCION] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ARM_ARMARIO_X_CODIGO_CALLE]
    ON [dbo].[Armarios]([CODIGO_CALLE] ASC);


GO

