CREATE TABLE [dbo].[autorizaciones] (
    [AUTORIZACION_ID]       INT      NOT NULL,
    [USUARIO_ID]            INT      NULL,
    [USUARIO_AUTORIZADO_ID] INT      NULL,
    [CLIENTE_SERVICIO_ID]   INT      NULL,
    [PERMISO_ID]            INT      NULL,
    [FECHA]                 DATETIME NULL,
    PRIMARY KEY CLUSTERED ([AUTORIZACION_ID] ASC),
    UNIQUE NONCLUSTERED ([CLIENTE_SERVICIO_ID] ASC, [PERMISO_ID] ASC),
    UNIQUE NONCLUSTERED ([CLIENTE_SERVICIO_ID] ASC, [USUARIO_AUTORIZADO_ID] ASC, [PERMISO_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [AUT_X_USUARIO_ID_Y_CLIENTE_SERVICIO_ID_Y_PERMISO_ID]
    ON [dbo].[autorizaciones]([USUARIO_ID] ASC, [CLIENTE_SERVICIO_ID] ASC, [PERMISO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [AUT_X_CLIENTE_SERVICIO_ID]
    ON [dbo].[autorizaciones]([CLIENTE_SERVICIO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [AUT_X_USUARIO_ID]
    ON [dbo].[autorizaciones]([USUARIO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [AUT_X_PERMISO_ID]
    ON [dbo].[autorizaciones]([PERMISO_ID] ASC);


GO

