CREATE TABLE [dbo].[categoria_iva_clasificacion_clientes] (
    [CATEGORIA_IVA_CLASIFICACION_CLIENTES_ID] INT NOT NULL,
    [CATEGORIA_IVA]                           INT NULL,
    [CLASIFICACION_CLIENTES]                  INT NULL,
    PRIMARY KEY CLUSTERED ([CATEGORIA_IVA_CLASIFICACION_CLIENTES_ID] ASC),
    UNIQUE NONCLUSTERED ([CLASIFICACION_CLIENTES] ASC, [CATEGORIA_IVA] ASC)
);


GO

CREATE NONCLUSTERED INDEX [CAT2_X_CLASIFICACION_ID]
    ON [dbo].[categoria_iva_clasificacion_clientes]([CLASIFICACION_CLIENTES] ASC);


GO

CREATE NONCLUSTERED INDEX [CAT2_X_CATEGORIA_ID]
    ON [dbo].[categoria_iva_clasificacion_clientes]([CATEGORIA_IVA] ASC);


GO

