CREATE TABLE [dbo].[Clasificacion_de_clientes] (
    [CLASIFICACION_DE_CLIENTES_ID] INT          NOT NULL,
    [DESCRIPCION]                  VARCHAR (19) NULL,
    [SERVICIO]                     VARCHAR (10) NULL,
    PRIMARY KEY CLUSTERED ([CLASIFICACION_DE_CLIENTES_ID] ASC),
    UNIQUE NONCLUSTERED ([DESCRIPCION] ASC, [SERVICIO] ASC)
);


GO

