CREATE TABLE [dbo].[Clientes_comentarios] (
    [CLIENTES_COMENTARIOS_ID] INT           NOT NULL,
    [CLIENTE_ID]              INT           NULL,
    [CLIENTE_SERVICIO_ID]     INT           NULL,
    [COMENTARIO]              VARCHAR (500) NULL,
    [FECHA]                   DATETIME      NULL,
    [operador]                VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([CLIENTES_COMENTARIOS_ID] ASC),
    UNIQUE NONCLUSTERED ([CLIENTE_SERVICIO_ID] ASC, [FECHA] ASC, [CLIENTES_COMENTARIOS_ID] ASC),
    UNIQUE NONCLUSTERED ([CLIENTE_SERVICIO_ID] ASC, [FECHA] ASC, [CLIENTES_COMENTARIOS_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [CLI3_CLIENTES_COMENTARIOS_ID_X_CLIENTE_SERVICIO_ID]
    ON [dbo].[Clientes_comentarios]([CLIENTE_SERVICIO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [CLI3_CLIENTES_COMENTARIOS_ID_X_CLIENTE_ID]
    ON [dbo].[Clientes_comentarios]([CLIENTE_ID] ASC);


GO

