CREATE TABLE [dbo].[Cliente] (
    [CLIENTE_ID]          INT          NOT NULL,
    [NOMBRE]              VARCHAR (60) NULL,
    [TIPO_DE_DOCUMENTO]   VARCHAR (4)  NULL,
    [NUMERO_DE_DOCUMENTO] DECIMAL (15) NULL,
    PRIMARY KEY CLUSTERED ([CLIENTE_ID] ASC),
    UNIQUE NONCLUSTERED ([NOMBRE] ASC, [CLIENTE_ID] ASC),
    UNIQUE NONCLUSTERED ([NUMERO_DE_DOCUMENTO] ASC, [TIPO_DE_DOCUMENTO] ASC)
);


GO

CREATE NONCLUSTERED INDEX [CLI1_POR_NOMBRE_SOLO]
    ON [dbo].[Cliente]([NOMBRE] ASC);


GO

