CREATE TABLE [dbo].[Clientes_servicios_Historico1] (
    [CLIENTES_SERVICIO_HISTORICO_ID] INT            NOT NULL,
    [NOMBRE_FANTASIA]                VARCHAR (55)   NULL,
    [CLIENTE_ID]                     INT            NULL,
    [CLIENTE_SERVICIO_ID]            INT            NULL,
    [NUMERADOR_HIJOS]                INT            NULL,
    [CLASIFICACION_DE_CLIENTES_ID]   INT            NULL,
    [TIPO_MODIFICACION]              VARCHAR (40)   NULL,
    [FECHA_MODIFICACION]             DATETIME       NULL,
    [CODIGO_CALLE]                   INT            NULL,
    [NUMERO]                         INT            NULL,
    [SECTOR]                         VARCHAR (2)    NULL,
    [BLOCK]                          VARCHAR (2)    NULL,
    [TORRE]                          VARCHAR (3)    NULL,
    [PISO]                           TINYINT        NULL,
    [DTO]                            VARCHAR (3)    NULL,
    [CASA]                           INT            NULL,
    [BARRIO]                         VARCHAR (15)   NULL,
    [LOCALIDAD_ID]                   INT            NULL,
    [CODIGO_POSTAL]                  VARCHAR (10)   NULL,
    [ENTRE_CODIGO_CALLE_1]           INT            NULL,
    [ENTRE_CODIGO_CALLE_2]           INT            NULL,
    [CODIGO_CALLE_P]                 INT            NULL,
    [CALLE_POSTAL]                   VARCHAR (40)   NULL,
    [NUMERO_P]                       INT            NULL,
    [SECTOR_P]                       VARCHAR (2)    NULL,
    [BLOCK_P]                        VARCHAR (2)    NULL,
    [TORRE_P]                        VARCHAR (3)    NULL,
    [PISO_P]                         TINYINT        NULL,
    [DTO_P]                          VARCHAR (3)    NULL,
    [CASA_P]                         INT            NULL,
    [BARRIO_P]                       VARCHAR (15)   NULL,
    [LOCALIDAD_ID_P]                 INT            NULL,
    [CODIGO_POSTAL_P]                VARCHAR (10)   NULL,
    [CLASIFICACION_SERVICIO]         INT            NULL,
    [SERVICIO]                       VARCHAR (10)   NULL,
    [NUMERO_TELEFONO]                INT            NULL,
    [PARTIDA]                        INT            NULL,
    [METROS_CUADRADOS_VIVIENDA]      DECIMAL (7, 2) NULL,
    [TIPO_DOC]                       VARCHAR (4)    NULL,
    [CLAVE]                          TINYINT        NULL,
    [NUMERO_DOC]                     VARCHAR (19)   NULL,
    [DIGITO_VERIFICADOR]             TINYINT        NULL,
    [DOCUMENTO]                      VARCHAR (20)   NULL,
    [CLASIFICACION_IVA_ID]           INT            NULL,
    [PIB]                            VARCHAR (2)    NULL,
    [PERCEPCION_ID]                  TINYINT        NULL,
    [FECHA_SUSPENCION]               DATETIME       NULL,
    [FECHA_TELECOBRANZA]             DATETIME       NULL,
    [FECHA_INTIMACION]               DATETIME       NULL,
    [FECHA_INSTALACION]              DATETIME       NULL,
    [FECHA_SOLICITUD]                DATETIME       NULL,
    [FECHA_HABILITACION]             DATETIME       NULL,
    [FECHA_BAJA]                     DATETIME       NULL,
    [FECHA_INGRESO_AL_SISTEMA]       DATETIME       NULL,
    [PLAN_COMERCIAL]                 INT            NULL,
    [ESTADO]                         TINYINT        NULL,
    [NUMERO_SOLICITUD]               INT            NULL,
    [CANTIDAD_DE_FACTURAS_ADEUDADAS] INT            NULL,
    [INTIMA]                         TINYINT        NULL,
    [VENDEDOR]                       INT            NULL,
    [FIGURACION_EN_GUIA]             VARCHAR (2)    NULL,
    [PERTENECE_A]                    VARCHAR (40)   NULL,
    [CUADRILLA]                      VARCHAR (20)   NULL,
    [OBSERVACIONES]                  VARCHAR (300)  NULL,
    [MOTIVO]                         VARCHAR (150)  NULL,
    [NO_GENERA_INTERESES]            TINYINT        NULL,
    [MODEM_ID]                       INT            NULL,
    [MODEM2_ID]                      INT            NULL,
    [TELEFONO_ID]                    INT            NULL,
    [PAR_ID]                         INT            NULL,
    [PUERTOS_ID]                     INT            NULL,
    [ORDEN_INSTALACION]              INT            NULL,
    [TIPO_CONEXION]                  VARCHAR (7)    NULL,
    [USER_NAME]                      VARCHAR (20)   NULL,
    [PASSWORD]                       VARCHAR (8)    NULL,
    [IP_1]                           TINYINT        NULL,
    [IP_2]                           TINYINT        NULL,
    [IP_3]                           TINYINT        NULL,
    [IP_4]                           TINYINT        NULL,
    [BAJADA]                         TINYINT        NULL,
    [F_E_ID]                         INT            NULL,
    [CANTIDAD_DE_BOCAS]              TINYINT        NULL,
    [CANTIDAD_DE_BOCAS_ADICIONALES]  TINYINT        NULL,
    [CANTIDAD_DE_BOCAS_EXISTENTES]   TINYINT        NULL,
    [HOUSING]                        TINYINT        NULL,
    [HOSTING]                        TINYINT        NULL,
    PRIMARY KEY CLUSTERED ([CLIENTES_SERVICIO_HISTORICO_ID] ASC),
    UNIQUE NONCLUSTERED ([CLIENTE_SERVICIO_ID] ASC, [CLIENTES_SERVICIO_HISTORICO_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [CLI131_CLIENTES_S_H_X_CLIENTE_ID]
    ON [dbo].[Clientes_servicios_Historico1]([CLIENTE_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [CLI131_CLIENTES_S_H_X_CLIENTE_SERVICIO_ID]
    ON [dbo].[Clientes_servicios_Historico1]([CLIENTE_SERVICIO_ID] ASC);


GO

