CREATE TABLE [dbo].[configuracion_lama] (
    [CONFIGURACION_LAMA_ID]   INT NOT NULL,
    [NUMERO_ORIGEN_INICIO]    INT NULL,
    [NUMERO_ORIGEN_A_TOMAR]   INT NULL,
    [NUMERO_DESTINO_INICIO]   INT NULL,
    [NUMERO_DESTINO_A_TOMAR]  INT NULL,
    [FECHA_LAMA_DIA_INICIO]   INT NULL,
    [FECHA_LAMA_DIA_TOMAR]    INT NULL,
    [FECHA_LAMA_MES_INICIO]   INT NULL,
    [FECHA_LAMA_MES_A_TOMAR]  INT NULL,
    [FECHA_LAMA_ANIO_INICIO]  INT NULL,
    [FECHA_LAMA_ANIO_A_TOMAR] INT NULL,
    [HORA_INICIO]             INT NULL,
    [HORA_A_TOMAR]            INT NULL,
    [HORA_MINUTOS_INICIO]     INT NULL,
    [HORA_MINUTOS_A_TOMAR]    INT NULL,
    [HORA_SEGUNDOS_INICIO]    INT NULL,
    [HORA_SEGUNDOS_A_TOMAR]   INT NULL,
    [SEGUNDOS_INICIO]         INT NULL,
    [SEGUNDOS_A_TOMAR]        INT NULL,
    PRIMARY KEY CLUSTERED ([CONFIGURACION_LAMA_ID] ASC)
);


GO

