CREATE TABLE [dbo].[EMPRESA] (
    [EMPRESA_ID] TINYINT       NOT NULL,
    [EMPRESA]    VARCHAR (40)  NULL,
    [DIRECCION]  VARCHAR (40)  NULL,
    [LOCALIDAD]  VARCHAR (40)  NULL,
    [PROVINCIA]  VARCHAR (40)  NULL,
    [CUIT]       VARCHAR (19)  NULL,
    [NRO_IB]     VARCHAR (19)  NULL,
    [NRO_GAN]    VARCHAR (19)  NULL,
    [LOGO]       VARCHAR (100) NULL,
    [CBU]        VARCHAR (50)  NULL,
    [Alias_CBU]  VARCHAR (90)  NULL,
    PRIMARY KEY CLUSTERED ([EMPRESA_ID] ASC)
);


GO

