CREATE TABLE [dbo].[Facturas] (
    [FACTURA_ID]          INT             NOT NULL,
    [QUE_ES]              VARCHAR (19)    NULL,
    [TIPO]                VARCHAR (1)     NULL,
    [NUMERO_FACTURA]      VARCHAR (19)    NULL,
    [SERVICIOS]           VARCHAR (19)    NULL,
    [PERIODO]             VARCHAR (10)    NULL,
    [PERIODO_ID]          INT             NULL,
    [PERIODO_CALCULO_ID]  INT             NULL,
    [ANULADO]             TINYINT         NULL,
    [IMPRESO]             TINYINT         NULL,
    [ORDEN_IMPRESION]     INT             NULL,
    [NOTA_DE_CREDITO]     VARCHAR (19)    NULL,
    [MOTIVO]              VARCHAR (20)    NULL,
    [CONTROL]             TINYINT         NULL,
    [CLIENTE_ID]          INT             NULL,
    [CLIENTE_SERVICIO_ID] INT             NULL,
    [CLASIFICACION_IVA]   TINYINT         NULL,
    [PERCEPCION_ID]       INT             NULL,
    [IMPORTE]             DECIMAL (15, 4) NULL,
    [SALDO]               DECIMAL (15, 4) NULL,
    [PARA_INTERESES]      DECIMAL (15, 4) NULL,
    [FECHA_EMISION]       DATETIME        NULL,
    [FECHA_VENCIMIENTO]   DATETIME        NULL,
    [FECHA_PAGO]          DATETIME        NULL,
    [NETO]                DECIMAL (11, 2) NULL,
    [NETO_2]              DECIMAL (11, 2) NULL,
    [IVA_1]               DECIMAL (11, 2) NULL,
    [IVA_2]               DECIMAL (11, 2) NULL,
    [EXENTO]              DECIMAL (11, 2) NULL,
    [IB]                  DECIMAL (11, 2) NULL,
    [PUESTO_ID]           INT             NULL,
    [DEBITO_AUTOMATICO]   TINYINT         NULL,
    [factura_de_credito]  TINYINT         NULL,
    PRIMARY KEY CLUSTERED ([FACTURA_ID] ASC),
    UNIQUE NONCLUSTERED ([TIPO] ASC, [NUMERO_FACTURA] ASC),
    UNIQUE NONCLUSTERED ([CLIENTE_SERVICIO_ID] ASC, [SERVICIOS] ASC, [PERIODO_ID] ASC, [QUE_ES] ASC),
    UNIQUE NONCLUSTERED ([PERIODO_ID] ASC, [FECHA_EMISION] ASC, [TIPO] ASC, [NUMERO_FACTURA] ASC, [FACTURA_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [FAC_X_CLIENTE_SERVICIO_Y_PERIODO]
    ON [dbo].[Facturas]([CLIENTE_SERVICIO_ID] ASC, [PERIODO] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_X_CLIENTE_ID_Y_ID]
    ON [dbo].[Facturas]([CLIENTE_ID] ASC, [FACTURA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_X_TIPO_Y_ORDEN_IMPRESION_Y_PERIODO]
    ON [dbo].[Facturas]([TIPO] ASC, [ORDEN_IMPRESION] ASC, [PERIODO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_POR_TIPO_Y_ID]
    ON [dbo].[Facturas]([TIPO] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_X_CLIENTE_SERVICIO_ID]
    ON [dbo].[Facturas]([CLIENTE_SERVICIO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTURAS_POR_PERIODO]
    ON [dbo].[Facturas]([PERIODO] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTUTAS_X_PERIODO_ID]
    ON [dbo].[Facturas]([PERIODO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_X_CLIENTE_SERVICIO_ID_Y_ID]
    ON [dbo].[Facturas]([FACTURA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTURAS_X_CONTROL]
    ON [dbo].[Facturas]([CONTROL] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTURAS_X_CLASIFICACION_IVA]
    ON [dbo].[Facturas]([CLASIFICACION_IVA] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTURAS_POR_SERVICIOS]
    ON [dbo].[Facturas]([SERVICIOS] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTURAS_X_IMPRESA_RUTA_ORDEN_ORDEN]
    ON [dbo].[Facturas]([IMPRESO] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_FACTURAS_POR_SERVICIOS_Y_FECHA]
    ON [dbo].[Facturas]([SERVICIOS] ASC, [FECHA_EMISION] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC_X_CLIENTE_ID]
    ON [dbo].[Facturas]([CLIENTE_ID] ASC);


GO

