CREATE TABLE [dbo].[Facturas_plan_de_pago] (
    [FACTURA_ID]          INT             NOT NULL,
    [NUMERO_FACTURA]      VARCHAR (19)    NULL,
    [SERVICIOS]           VARCHAR (19)    NULL,
    [PERIODO]             VARCHAR (10)    NULL,
    [CLIENTE_ID]          INT             NULL,
    [CLIENTE_SERVICIO_ID] INT             NULL,
    [IMPORTE]             DECIMAL (15, 4) NULL,
    [FECHA_VENCIMIENTO]   DATETIME        NULL,
    [INTERES]             DECIMAL (9, 2)  NULL,
    [IVA_INTERES]         DECIMAL (9, 2)  NULL,
    PRIMARY KEY CLUSTERED ([FACTURA_ID] ASC),
    UNIQUE NONCLUSTERED ([NUMERO_FACTURA] ASC),
    UNIQUE NONCLUSTERED ([NUMERO_FACTURA] ASC, [FACTURA_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [FAC6_FACTURAS_POR_SERVICIOS_Y_FECHA]
    ON [dbo].[Facturas_plan_de_pago]([SERVICIOS] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_CLIENTE_SERVICIO_Y_PERIODO]
    ON [dbo].[Facturas_plan_de_pago]([CLIENTE_SERVICIO_ID] ASC, [PERIODO] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_CLIENTE_SERVICIO_ID]
    ON [dbo].[Facturas_plan_de_pago]([CLIENTE_SERVICIO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_CLIENTE_SERVICIO_ID_Y_ID]
    ON [dbo].[Facturas_plan_de_pago]([CLIENTE_SERVICIO_ID] ASC, [FACTURA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_FACTURAS_POR_SERVICIOS]
    ON [dbo].[Facturas_plan_de_pago]([SERVICIOS] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_TIPO_Y_NUMERO_FACTURA_Y_PERIODO_ID]
    ON [dbo].[Facturas_plan_de_pago]([NUMERO_FACTURA] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_CLIENTE_SERVICIO_ID_Y_SERVICIO_Y_PERIODO_ID_Y_QUE_ES]
    ON [dbo].[Facturas_plan_de_pago]([CLIENTE_SERVICIO_ID] ASC, [SERVICIOS] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_CLIENTE_ID]
    ON [dbo].[Facturas_plan_de_pago]([CLIENTE_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_X_CLIENTE_ID_Y_ID]
    ON [dbo].[Facturas_plan_de_pago]([CLIENTE_ID] ASC, [FACTURA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [FAC6_FACTURAS_POR_PERIODO]
    ON [dbo].[Facturas_plan_de_pago]([PERIODO] ASC);


GO

