CREATE TABLE [dbo].[Generador_QR] (
    [NRO_FACTURA]       VARCHAR (15)  NOT NULL,
    [INTENCION_DE_PAGO] VARCHAR (259) NULL,
    [ESTADO]            TINYINT       NULL,
    [FECHA_CREACION]    DATETIME      NULL,
    [FECHA_UPDATE]      DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([NRO_FACTURA] ASC)
);


GO

CREATE TRIGGER [dbo].[TR_UPDATE_GENERADOR_QR_FECHA_UPDATE]
ON [dbo].[Generador_QR]
FOR UPDATE
AS
BEGIN
	UPDATE [dbo].[Generador_QR]
	SET FECHA_UPDATE = GETDATE()
	FROM inserted
	WHERE [dbo].[Generador_QR].NRO_FACTURA = inserted.NRO_FACTURA
END;

GO

