CREATE TABLE [dbo].[Items_planes_comerciales] (
    [ITEM_PLANE_COMERCIAL_ID] INT     NOT NULL,
    [PLAN_COMERCIAL_ID]       INT     NULL,
    [ITEM_FACTURACION_ID]     INT     NULL,
    [ORDEN]                   INT     NULL,
    [SUSPENDIDO]              TINYINT NULL,
    PRIMARY KEY CLUSTERED ([ITEM_PLANE_COMERCIAL_ID] ASC),
    UNIQUE NONCLUSTERED ([PLAN_COMERCIAL_ID] ASC, [ITEM_FACTURACION_ID] ASC),
    UNIQUE NONCLUSTERED ([ORDEN] ASC, [ITEM_FACTURACION_ID] ASC, [PLAN_COMERCIAL_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ITE1_ITEM_PLAN_COMERCIAL_X_PLAN_ID]
    ON [dbo].[Items_planes_comerciales]([PLAN_COMERCIAL_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [ITE1_ITEM_PLAN_COMERCIAL_X_ITEM_ID]
    ON [dbo].[Items_planes_comerciales]([ITEM_FACTURACION_ID] ASC);


GO

