CREATE TABLE [dbo].[lamas_grabados] (
    [LAMAS_GRABADOS_ID] INT NOT NULL,
    [NUMERO_LAMA]       INT NULL,
    PRIMARY KEY CLUSTERED ([LAMAS_GRABADOS_ID] ASC),
    UNIQUE NONCLUSTERED ([NUMERO_LAMA] ASC)
);


GO

