CREATE TABLE [dbo].[mails] (
    [MAILS_ID]            INT           NOT NULL,
    [CLIENTE_SERVICIO_ID] INT           NULL,
    [MAIL]                VARCHAR (100) NULL,
    [CUOTA]               INT           NULL,
    [ITEM_HOSTING_ID]     INT           NULL,
    [estado]              TINYINT       NULL,
    PRIMARY KEY CLUSTERED ([MAILS_ID] ASC),
    CONSTRAINT [MAI_X_MAIL_Y_CLIENTE_SERVICIO_ID] UNIQUE NONCLUSTERED ([MAIL] ASC, [CLIENTE_SERVICIO_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [MAI_X_ITEM_HOSTING_ID]
    ON [dbo].[mails]([ITEM_HOSTING_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [UQ__mails__7F36D027]
    ON [dbo].[mails]([MAIL] ASC);


GO

CREATE NONCLUSTERED INDEX [MAI_X_MAIL_Y_ITEM_HOSTING_ID]
    ON [dbo].[mails]([MAIL] ASC, [ITEM_HOSTING_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [MAI_X_CLIENTE_SERVICIO_ID]
    ON [dbo].[mails]([CLIENTE_SERVICIO_ID] ASC);


GO

