CREATE TABLE [dbo].[manzanas] (
    [MANZANA_ID]  INT          NOT NULL,
    [DESCRIPCION] VARCHAR (30) NULL,
    [MANZANA]     VARCHAR (6)  NULL,
    [FMC]         VARCHAR (8)  NULL,
    [SECCION]     VARCHAR (7)  NULL,
    [RADIO]       VARCHAR (5)  NULL,
    PRIMARY KEY CLUSTERED ([MANZANA_ID] ASC),
    UNIQUE NONCLUSTERED ([MANZANA] ASC, [MANZANA_ID] ASC),
    UNIQUE NONCLUSTERED ([RADIO] ASC, [MANZANA_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [MAN_MANZANA_X_SECCION]
    ON [dbo].[manzanas]([SECCION] ASC);


GO

CREATE NONCLUSTERED INDEX [xradio]
    ON [dbo].[manzanas]([RADIO] ASC);


GO

