CREATE TABLE [dbo].[numerador_iva] (
    [NUMERADOR_ID]             INT NOT NULL,
    [VENTAS_INTERNET_P_INICIO] INT NULL,
    [VENTAS_INTERNET_P_FINAL]  INT NULL,
    PRIMARY KEY CLUSTERED ([NUMERADOR_ID] ASC)
);


GO

