CREATE TABLE [dbo].[operadores] (
    [OPERADOR_ID]     INT          NOT NULL,
    [NOMBRE_OPERADOR] VARCHAR (39) NULL,
    [CLAVE_OPERADOR]  VARCHAR (19) NULL,
    PRIMARY KEY CLUSTERED ([OPERADOR_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [OPE_POR_NOMBRE]
    ON [dbo].[operadores]([NOMBRE_OPERADOR] ASC);


GO

