CREATE TABLE [dbo].[Parametros_factura_web] (
    [ID]                     INT NOT NULL,
    [PARAMETRO_ID_TELEFONIA] INT NULL,
    [PARAMETRO_ID_INTERNET]  INT NULL,
    [PUESTO_A_ID_TELEFONIA]  INT NULL,
    [PUESTO_B_ID_TELEFONIA]  INT NULL,
    [PUESTO_A_ID_INTERNET]   INT NULL,
    [PUESTO_B_ID_INTERNET]   INT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

