CREATE TABLE [dbo].[parametros] (
    [PARAMETROS_ID]                                        INT             NOT NULL,
    [IP_FIJA]                                              INT             NULL,
    [F_EN_GUIA]                                            INT             NULL,
    [fecha_gestion_de_deuda]                               DATETIME        NULL,
    [dias_intima]                                          INT             NULL,
    [dias_suspencion]                                      INT             NULL,
    [dias_corte]                                           INT             NULL,
    [fecha_gestion_de_deuda_telefonia]                     DATETIME        NULL,
    [dias_intima_telefonia_1]                              INT             NULL,
    [dias_intima_telefonia_2]                              INT             NULL,
    [dias_corte_telefonia]                                 INT             NULL,
    [dias_suspencion_telefonia]                            INT             NULL,
    [numero_intimacion]                                    INT             NULL,
    [item_bocas_adicionales_id]                            INT             NULL,
    [item_mantenimiento_bocas_adicionales_id]              INT             NULL,
    [item_bocas_adicionales_modificacion_id]               INT             NULL,
    [item_mantenimiento_bocas_adicionales_modificacion_id] INT             NULL,
    [item_ba_modificacion_2_id]                            INT             NULL,
    [item_mantenimiento_ba_modificacion_2_id]              INT             NULL,
    [plan_de_pago]                                         INT             NULL,
    [item_intereses_plan_de_pago_id]                       INT             NULL,
    [item_cuota_plan_de_pago_id]                           INT             NULL,
    [item_anticipo_id]                                     INT             NULL,
    [dolar]                                                DECIMAL (18, 2) NULL,
    [dias_numero_telefonico]                               TINYINT         NULL,
    [dias_mantencion_par]                                  TINYINT         NULL,
    [dias_mantencion_puerto]                               TINYINT         NULL,
    [fecha_gestion_de_planes_de_pago]                      DATETIME        NULL,
    [dias_plan_de_pago_internet]                           TINYINT         NULL,
    [dias_plan_de_pago_telefonia]                          TINYINT         NULL,
    [dias_prorroga_habilitacion_vencimiento]               TINYINT         NULL,
    [valor_ama_local]                                      DECIMAL (18, 9) NULL,
    [valor_ama_ld]                                         DECIMAL (18, 9) NULL,
    [valor_ama_cer]                                        DECIMAL (18, 9) NULL,
    [fecha_personal]                                       DATETIME        NULL,
    [fecha_movistar]                                       DATETIME        NULL,
    [fecha_claro]                                          DATETIME        NULL,
    [cer]                                                  DECIMAL (18, 4) NULL,
    [fecha_cer]                                            DATETIME        NULL,
    [prejudicial]                                          DECIMAL (18, 2) NULL,
    [mail_dvr]                                             VARCHAR (100)   NULL,
    [item_cuota_dvr_id]                                    INT             NULL,
    [cuenta_dvr_debe]                                      INT             NULL,
    [cuenta_dvr_haber]                                     INT             NULL,
    [item_cargo_telefonia]                                 INT             NULL,
    [item_cargo_internet]                                  INT             NULL,
    [item_cargo_telefonia_mas60]                           INT             NULL,
    [item_cargo_internet_mas60]                            INT             NULL,
    [fecha_nextel]                                         DATETIME        NULL,
    [importe_tierra]                                       DECIMAL (12, 8) NULL,
    [importe_aire]                                         DECIMAL (12, 8) NULL,
    [valor_min_para_ib]                                    DECIMAL (18, 2) NULL,
    [min_tasa]                                             DECIMAL (12, 3) NULL,
    [min_acerca]                                           DECIMAL (12, 3) NULL,
    CONSTRAINT [PK__parametros__4850AF91] PRIMARY KEY CLUSTERED ([PARAMETROS_ID] ASC)
);


GO

