CREATE TABLE [dbo].[Percepciones_cpp] (
    [PERCEPCION_CPP_ID]   INT NOT NULL,
    [PERCEPCION_ID]       INT NULL,
    [PRESTATARIA_CPP_ID]  INT NULL,
    [ITEM_FACTURACION_ID] INT NULL,
    PRIMARY KEY CLUSTERED ([PERCEPCION_CPP_ID] ASC),
    UNIQUE NONCLUSTERED ([PRESTATARIA_CPP_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [PR11_X_PERCEPCION_ID]
    ON [dbo].[Percepciones_cpp]([PERCEPCION_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [PR11_X_PERCEPCION_IDD_Y_PRESTATARIA_CPP_ID]
    ON [dbo].[Percepciones_cpp]([PERCEPCION_ID] ASC, [PRESTATARIA_CPP_ID] ASC);


GO

