CREATE TABLE [dbo].[Placas] (
    [PLACA_ID]            INT          NOT NULL,
    [POSICION_EQUIPO_ID]  INT          NULL,
    [DESCRIPCION]         VARCHAR (30) NULL,
    [NUMERO_DE_PLACA]     VARCHAR (50) NULL,
    [NUMERO_DE_POSICION]  TINYINT      NULL,
    [CANTIDAD_DE_PUERTOS] INT          NULL,
    [DATOS]               TINYINT      NULL,
    [VOZ]                 TINYINT      NULL,
    [VIDEO]               TINYINT      NULL,
    [habilitada]          TINYINT      NULL,
    CONSTRAINT [PK__Placas__24B26D99] PRIMARY KEY CLUSTERED ([PLACA_ID] ASC),
    CONSTRAINT [UQ__Placas__25A691D2] UNIQUE NONCLUSTERED ([POSICION_EQUIPO_ID] ASC, [PLACA_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [PLA_PLACAS_X_EQUIPO_Y_NUMERO_DE_PLACA]
    ON [dbo].[Placas]([POSICION_EQUIPO_ID] ASC, [NUMERO_DE_PLACA] ASC);


GO

CREATE NONCLUSTERED INDEX [PLA_PLACAS_X_POSICION_EQUIPO_ID]
    ON [dbo].[Placas]([POSICION_EQUIPO_ID] ASC);


GO

