CREATE TABLE [dbo].[planes_telefonia_internet] (
    [PLANES_TELEFONIA_INTERNET_ID] INT NOT NULL,
    [PLAN_TELEFONIA_ID]            INT NULL,
    [PLAN_INTERNET_ID]             INT NULL,
    PRIMARY KEY CLUSTERED ([PLANES_TELEFONIA_INTERNET_ID] ASC),
    UNIQUE NONCLUSTERED ([PLAN_TELEFONIA_ID] ASC, [PLAN_INTERNET_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [PLA2_X_PLAN_TELEFONIA]
    ON [dbo].[planes_telefonia_internet]([PLAN_TELEFONIA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [PLA2_X_PLAN_INTERNET]
    ON [dbo].[planes_telefonia_internet]([PLAN_INTERNET_ID] ASC);


GO

