CREATE TABLE [dbo].[Posiciones_equipos] (
    [POSICION_EQUIPOS_ID] INT     NOT NULL,
    [EQUIPOS_ID]          INT     NULL,
    [OCUPADO]             TINYINT NULL,
    [PLACA_ID]            INT     NULL,
    [POSICION]            TINYINT NULL,
    PRIMARY KEY CLUSTERED ([POSICION_EQUIPOS_ID] ASC),
    UNIQUE NONCLUSTERED ([EQUIPOS_ID] ASC, [POSICION] ASC)
);


GO

CREATE NONCLUSTERED INDEX [POS1_POSICIONES_EQUIPOS_ID_Y_PLACA_ID]
    ON [dbo].[Posiciones_equipos]([EQUIPOS_ID] ASC, [PLACA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [POS1_POSICIONES_EQUIPOS_X_PLACA_ID]
    ON [dbo].[Posiciones_equipos]([PLACA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [POS1_POSICIONES_EQUIPOS_X_EQUIPOS_ID]
    ON [dbo].[Posiciones_equipos]([EQUIPOS_ID] ASC);


GO

