CREATE TABLE [dbo].[Prestatarias] (
    [PRESTATARIAS_ID]     INT          NOT NULL,
    [PRESTATARIA]         VARCHAR (40) NULL,
    [ARCHIVO]             CHAR (41)    NULL,
    [ITEM_FACTURACION_ID] INT          NULL,
    [INICIO_ARCHIVO]      INT          NULL,
    [FECHA_ARCHIVO]       DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([PRESTATARIAS_ID] ASC),
    UNIQUE NONCLUSTERED ([PRESTATARIA] ASC)
);


GO

CREATE NONCLUSTERED INDEX [PRE1_PRESTATARIAS_X_ITEMS_FACTURACION_ID]
    ON [dbo].[Prestatarias]([ITEM_FACTURACION_ID] ASC);


GO

