CREATE TABLE [dbo].[Puertos_ocupados] (
    [PUERTO_ID]           INT           NOT NULL,
    [CLIENTE_SERVICIO_ID] INT           NULL,
    [DIRECCION_IP]        VARCHAR (40)  NULL,
    [NRO_PUERTO]          VARCHAR (40)  NULL,
    [TIPO_PUERTO]         VARCHAR (40)  NULL,
    [APLICACION]          VARCHAR (100) NULL,
    [FECHA]               DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([PUERTO_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [PUE_KEY_NRO_PUERTO]
    ON [dbo].[Puertos_ocupados]([NRO_PUERTO] ASC);


GO

CREATE NONCLUSTERED INDEX [PUE_KEY_CLIENTE_SERVICIO_ID]
    ON [dbo].[Puertos_ocupados]([CLIENTE_SERVICIO_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [PUE_KEY_TIPO_PUERTO]
    ON [dbo].[Puertos_ocupados]([TIPO_PUERTO] ASC);


GO

CREATE NONCLUSTERED INDEX [PUE_KEY_PUERTO_CLIENTE_NRO_PUERTO]
    ON [dbo].[Puertos_ocupados]([PUERTO_ID] ASC, [CLIENTE_SERVICIO_ID] ASC, [NRO_PUERTO] ASC);


GO

CREATE NONCLUSTERED INDEX [PUE_KEY_APLICACION]
    ON [dbo].[Puertos_ocupados]([APLICACION] ASC);


GO

CREATE NONCLUSTERED INDEX [PUE_KEY_DIRECCION_IP]
    ON [dbo].[Puertos_ocupados]([DIRECCION_IP] ASC);


GO

