CREATE TABLE [dbo].[rechazo] (
    [RECHAZO_ID]  INT           NOT NULL,
    [DESCRIPCION] VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([RECHAZO_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [SOL_KEY_SERVICIO_DESCRIPCION]
    ON [dbo].[rechazo]([DESCRIPCION] ASC);


GO

