CREATE TABLE [dbo].[S_Anticipos] (
    [ID_ANTICIPOS]     INT            NOT NULL,
    [CODIGO_EMPLEADO]  INT            NULL,
    [IMPORTE_ANTICIPO] DECIMAL (9, 2) NULL,
    [DETALLE]          VARCHAR (29)   NULL,
    [CTA_ANTICIPOS]    VARCHAR (20)   NULL,
    [FECHA]            INT            NULL,
    PRIMARY KEY CLUSTERED ([ID_ANTICIPOS] ASC),
    UNIQUE NONCLUSTERED ([CODIGO_EMPLEADO] ASC, [ID_ANTICIPOS] ASC)
);


GO

CREATE NONCLUSTERED INDEX [ANT1_ANTICIPO_X_COD_EMPLEADO]
    ON [dbo].[S_Anticipos]([CODIGO_EMPLEADO] ASC);


GO

