CREATE TABLE [dbo].[S_para_sueldos] (
    [ID_PARAMETRO]       INT          NOT NULL,
    [CTA_PARA_ANTICIPOS] VARCHAR (20) NULL,
    [RECIBO_EN_LASER]    TINYINT      NULL,
    PRIMARY KEY CLUSTERED ([ID_PARAMETRO] ASC)
);


GO

