CREATE TABLE [dbo].[sql] (
    [A1] VARCHAR (40) NULL,
    [A2] VARCHAR (40) NULL,
    [A3] VARCHAR (40) NULL,
    [A4] VARCHAR (40) NULL,
    [A5] VARCHAR (40) NULL,
    [A6] VARCHAR (40) NULL,
    [A7] VARCHAR (40) NULL,
    [A8] VARCHAR (40) NULL
);


GO

