CREATE TABLE [dbo].[ss_USERINGROUP] (
    [USERNO] INT NOT NULL,
    [UGRPNO] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([USERNO] ASC, [UGRPNO] ASC),
    UNIQUE NONCLUSTERED ([UGRPNO] ASC, [USERNO] ASC)
);


GO

