CREATE TABLE [dbo].[subtotales] (
    [SUBTOTALES_ID] INT          NOT NULL,
    [DESCRIPCION]   VARCHAR (20) NULL,
    [SERVICIOS]     VARCHAR (19) NULL,
    PRIMARY KEY CLUSTERED ([SUBTOTALES_ID] ASC),
    UNIQUE NONCLUSTERED ([DESCRIPCION] ASC, [SERVICIOS] ASC)
);


GO

CREATE NONCLUSTERED INDEX [SUB1_SUBTOTALES_X_SERVICIO]
    ON [dbo].[subtotales]([SERVICIOS] ASC);


GO

