CREATE TABLE [dbo].[subzonas] (
    [ZONA]        INT          NULL,
    [SUBZONA]     VARCHAR (5)  NOT NULL,
    [DESCRIPCION] VARCHAR (30) NULL,
    PRIMARY KEY CLUSTERED ([SUBZONA] ASC),
    UNIQUE NONCLUSTERED ([DESCRIPCION] ASC)
);


GO

CREATE NONCLUSTERED INDEX [SUB_SUBZONA_X_ZONA]
    ON [dbo].[subzonas]([ZONA] ASC);


GO

