CREATE TABLE [dbo].[tagsave] (
    [TAGASAVE_ID] INT NOT NULL,
    [REGISTRO]    INT NULL,
    PRIMARY KEY CLUSTERED ([TAGASAVE_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [TAG_X_REGISTRO]
    ON [dbo].[tagsave]([REGISTRO] ASC);


GO

