CREATE TABLE [dbo].[Tipo_de_debito_automatico] (
    [TIPO_DE_DEBITO_AUTOMATICO_ID] INT          NOT NULL,
    [TIPO_DE_DEBITO]               VARCHAR (30) NULL,
    PRIMARY KEY CLUSTERED ([TIPO_DE_DEBITO_AUTOMATICO_ID] ASC),
    UNIQUE NONCLUSTERED ([TIPO_DE_DEBITO] ASC)
);


GO

