CREATE TABLE [dbo].[Tipo_Respuesta] (
    [TIPO_RESPUESTA_ID] INT           NOT NULL,
    [DESCRIPCION]       VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([TIPO_RESPUESTA_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [TIP2_X_ID]
    ON [dbo].[Tipo_Respuesta]([TIPO_RESPUESTA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [TIP2_KEY_SERVICIO_DESCRIPCION_DERIVAR_A]
    ON [dbo].[Tipo_Respuesta]([DESCRIPCION] ASC);


GO

CREATE NONCLUSTERED INDEX [TIP2_KEY_SERVICIO_AGRUPA_TIPO]
    ON [dbo].[Tipo_Respuesta]([DESCRIPCION] ASC);


GO

