CREATE TABLE [dbo].[ubicaciones] (
    [UBICACIONES_ID] INT          NOT NULL,
    [CODIGO_CALLE]   INT          NULL,
    [CROQUIS]        VARCHAR (10) NULL,
    [DESDE]          INT          NULL,
    [HASTA]          INT          NULL,
    [MANZANA_ID]     INT          NULL,
    [PARES_IMPARES]  VARCHAR (1)  NULL,
    [ZONA]           TINYINT      NULL,
    PRIMARY KEY CLUSTERED ([UBICACIONES_ID] ASC),
    UNIQUE NONCLUSTERED ([CROQUIS] ASC),
    UNIQUE NONCLUSTERED ([MANZANA_ID] ASC, [CROQUIS] ASC)
);


GO

CREATE NONCLUSTERED INDEX [UBI_UBICACIONES_X_CODIGO_CALLE_Y_DESDE]
    ON [dbo].[ubicaciones]([CODIGO_CALLE] ASC, [DESDE] ASC);


GO

CREATE NONCLUSTERED INDEX [UBI_UBICACIONES_X_MANZANA_ID]
    ON [dbo].[ubicaciones]([MANZANA_ID] ASC);


GO

CREATE NONCLUSTERED INDEX [UBI_UBICACIONES_X_CODIGO_DE_CALLE]
    ON [dbo].[ubicaciones]([CODIGO_CALLE] ASC);


GO

CREATE NONCLUSTERED INDEX [UBI_UBICACIONES_X_ZONA]
    ON [dbo].[ubicaciones]([ZONA] ASC);


GO

