CREATE TABLE [dbo].[Usuarios_localidades_habilitadas] (
    [USUARIOS_LOCALIDADES_HABILITADAS_ID] INT NOT NULL,
    [USUARIO_ID]                          INT NULL,
    [LOCALIDAD_ID]                        INT NULL,
    PRIMARY KEY CLUSTERED ([USUARIOS_LOCALIDADES_HABILITADAS_ID] ASC),
    UNIQUE NONCLUSTERED ([LOCALIDAD_ID] ASC, [USUARIO_ID] ASC),
    UNIQUE NONCLUSTERED ([USUARIO_ID] ASC, [LOCALIDAD_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [USU_X_LOCALIDAD_SOLA]
    ON [dbo].[Usuarios_localidades_habilitadas]([LOCALIDAD_ID] ASC);


GO

