CREATE TABLE [dbo].[vendedores] (
    [VENDEDOR_ID]       INT          NOT NULL,
    [APELLIDO_Y_NOMBRE] VARCHAR (30) NULL,
    PRIMARY KEY CLUSTERED ([VENDEDOR_ID] ASC),
    UNIQUE NONCLUSTERED ([APELLIDO_Y_NOMBRE] ASC)
);


GO

