CREATE TABLE [dbo].[zonas] (
    [ZONA]        INT          NOT NULL,
    [DESCRIPCION] VARCHAR (30) NULL,
    PRIMARY KEY CLUSTERED ([ZONA] ASC),
    UNIQUE NONCLUSTERED ([DESCRIPCION] ASC)
);


GO

