-- CLIENTES SIN SERVICIOS
SELECT 
C.CLIENTE_ID, C.TIPO_DOC, C.DOCUMENTO,
S.CLIENTE_ID, S.CLIENTE_SERVICIO_ID, S.TIPO_DOC, S.DOCUMENTO
FROM clientes AS C 
LEFT JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE S.TIPO_DOC IS NULL

-- SERVICIOS SIN CLIENTE
SELECT 
C.CLIENTE_ID, C.TIPO_DOC, C.DOCUMENTO,
S.CLIENTE_ID, S.CLIENTE_SERVICIO_ID, S.TIPO_DOC, S.DOCUMENTO
FROM clientes AS C 
RIGHT JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE C.TIPO_DOC IS NULL

-- SERVICIOS CON DOC TIPO DOC != CLIENTES
SELECT TOP 3
C.CLIENTE_ID, C.TIPO_DOC, C.DOCUMENTO,
S.CLIENTE_ID, S.CLIENTE_SERVICIO_ID, S.TIPO_DOC, S.DOCUMENTO
FROM clientes AS C 
INNER JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE C.TIPO_DOC <> S.TIPO_DOC 

-- SERVICIOS CON TIPO DOC DISTINTO A CLIENTE
SELECT COUNT(*) AS TIPO_DISTINTO
FROM clientes AS C 
INNER JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE C.TIPO_DOC <> S.TIPO_DOC 

-- SERVICIOS CON TIPO DOC DISTINTO A CLIENTE
SELECT COUNT(*) AS DOC_DISTINTO
FROM clientes AS C 
INNER JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE C.DOCUMENTO <> S.DOCUMENTO 

-- SERVICIOS CON TIPO O DOC DISTINTO A CLIENTE
SELECT COUNT(*) AS DOCoTIPO_DISTINTOS
FROM clientes AS C 
INNER JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE C.DOCUMENTO <> S.DOCUMENTO 
OR C.TIPO_DOC <> S.TIPO_DOC 

-- SERVICIOS CON TIPO Y DOC DISTINTO A CLIENTE
SELECT COUNT(*) AS DOCYTIPO_DISTINTOS
FROM clientes AS C 
INNER JOIN Clientes_servicios AS S 
ON C.CLIENTE_ID = S.CLIENTE_ID
WHERE C.DOCUMENTO <> S.DOCUMENTO 
AND C.TIPO_DOC <> S.TIPO_DOC 

-- TOTAL CLIENTES
SELECT COUNT(*) AS NRO_CLIENTES FROM clientes

-- TOTAL SERVICIOS
SELECT COUNT(*) AS NRO_SERVICIOS FROM Clientes_servicios

-- CANTIDAD DE SERVICIOS POR ESTADO
SELECT Clientes_servicios.ESTADO , COUNT(*) as CANTIDAD
FROM Clientes_servicios
GROUP BY ESTADO

-- CANTIDAD DE SERVICIOS POR TIPO_DOC
SELECT Clientes_servicios.TIPO_DOC , COUNT(*) as CANTIDAD
FROM Clientes_servicios
GROUP BY TIPO_DOC

-- CANTIDAD POR ESTADO Y SERVICIO
SELECT SERVICIO, ESTADO, COUNT(SERVICIO) AS CANTIDAD
FROM Clientes_servicios
GROUP BY SERVICIO, ESTADO
ORDER BY SERVICIO, ESTADO

-- NOMBRE DISTINTOS EN SERVICIO
SELECT 
CL.APELLIDO_NOMBRES_RAZON_SOCIAL AS C_NOMBRE, 
SR.CLIENTE_SERVICIO_ID AS SERVICIO_ID,
SR.CIS AS CIS,
SR.Nombre_cliente AS S_CLIENTE, 
SR.nombre_titular AS S_TITULAR,
sr.nombre_fantasia AS S_FANTASIA,
CL.TIPO_DOC AS C_TIPO,
CL.DOCUMENTO AS C_DOC,
SR.TIPO_DOC AS S_TIPO,
SR.DOCUMENTO AS S_DOC
FROM DBO.Clientes_servicios AS SR
INNER JOIN clientes AS CL
ON SR.CLIENTE_ID = CL.CLIENTE_ID
WHERE 
SR.Nombre_cliente NOT LIKE SR.nombre_titular

-- Servicios a Facturar
-- SERVICIO= 'Internet' 'Telefonia' 'Varios'
DECLARE @HABILITADO AS INTEGER = 3
DECLARE @SUSPENDIDO AS INTEGER = 5

DECLARE @HAB_HASTA AS DATE = '20240809'

DECLARE @SUS_DESDE AS DATE = '20240801'
DECLARE @SUS_HASTA AS DATE = '20240101'

DECLARE @INCLUSION_DESDE AS DATE = '20240101'
DECLARE @INCLUSION_HASTA AS DATE = '20241231'

DECLARE @SERVICIO AS VARCHAR(25)  = 'Internet'

SELECT --TOP 100 
COUNT (CLIENTE_SERVICIO_ID)
FROM Clientes_servicios  
WHERE 
(Fecha_Habilitacion <= @HAB_HASTA AND servicio = @SERVICIO) 
AND  
(
    ESTADO = @HABILITADO     
    OR (ESTADO = @HABILITADO AND fecha_suspencion < @SUS_HASTA) 
    OR (ESTADO = @SUSPENDIDO AND fecha_suspencion >= @SUS_DESDE)
)
AND (fecha_proxima_inclusion >= @INCLUSION_DESDE AND fecha_proxima_inclusion <= @INCLUSION_HASTA)
OR (plan_de_pago = 1 AND servicio = @SERVICIO) 
OR (cuota_dvr = 1 AND servicio = @SERVICIO)
