/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dbacerca;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Driver;
import java.sql.DriverManager;

import java.util.Enumeration;

public class App {

  public static void main(String[] args) {

    /*
     * 
     * Servidor: SERVER-GESTION / 192.168.1.190
     * DB: telefonia
     * Usuario: sysacerca
     * Contraseña: SoloAcerca28+
     * 
     */

    String connectionUrl = "jdbc:sqlserver://192.168.1.190;"
        + "database=telefonia;"
        + "user=sysacerca;"
        + "password=SoloAcerca28+;"
        + "encrypt=false;"
        + "trustServerCertificate=true;"
        + "loginTimeout=5;";

    System.out.println(connectionUrl);
    Enumeration<Driver> drivers = DriverManager.getDrivers();

    while (drivers.hasMoreElements()) {
      Driver drv = drivers.nextElement();
      String name = drv.toString() + "-v" + drv.getMajorVersion() + "." + drv.getMinorVersion();
      System.out.println(name);
    }

    // System.out.println("iterator");

    // drivers = DriverManager.getDrivers();
    // drivers.asIterator().forEachRemaining(
    // (drv) -> {
    // String name = drv.toString() + "-v" + drv.getMajorVersion() + "." +
    // drv.getMinorVersion();
    // System.out.println(name);
    // });

    try (Connection connection = DriverManager.getConnection(connectionUrl);) {
      // Code here.
      System.out.println("Conectado");

      connection.close();

    }
    // Handle any errors that may have occurred.
    catch (SQLException e) {
      e.printStackTrace();
    }
  }

}
